language: node_js
node_js:
- '7'
cache: yarn
before_install:
- npm install --global npm@latest
before_script:
- npm prune
after_success:
- npm run coveralls
notifications:
  slack:
    secure: A71W7ennsPU8SpP938cWgYYRE56smK8zoOmND9uv+tfEP57jS0R43WmtLcmdzFppJbL8unuqy19PP/6mwg5hGdWx29FRLDYlREJfxNdKAcUjF8IvkKyvYyhR5TToxdc5FBRWJzWvlXON+ehyA8RXP1z5TqI7u0fOR8B1YPYnV7DP0HDVx5AAwFi7ThI6Z+vbtV6mZz2P8eq+Fhbgck+eqtWf7ciwUZ/3MOUsPHXADXTZYuEMpB8YM0mZTADczD/YCciG3qtqo6JdEBQnMDQ0uab9RhJmFOCNAFVysAj0vmaIY3H/vK9WqKMKNu9hQc28hTuv2gyOAGw6vHzb//OVUv5vNkTo35R2A2P3bGiiEO4Agc3ee9+/k9gx2oosa7vVVk7e00Am3FcA+vPY+CNg8SiAE5dmJOwm95/6ByvyRyG5J0+PdY5yHPan+aZjFV4Tw0gTNmDTkV1tbpwNPklcyWJqg9Vsf2rQQ4qHJ1rQGfs/9xzfGyToJ30AfRT4M9+YoDygfp7aQVIDPbeWo2y++yxCgcRJR03NIjz13UNSGUAFxFqpyFOn5bQ86F25hiIbIk1WdMl8UdEIfgsoFufPfq4CoQbSv1wF4h+Eanh/89Y5yl+lORYG5apEKF3BSO58zsCS73SHHIYrPENiq843UUfRrn2koDKEWr7IiWtwP9w=
