module.exports = {
  'content-font-size': 'ཡི་གེ་ཆེ་ཆུང་།',
  'cancel-importing': 'སུབས་ཤིག །',
  'account': 'དྲྭ་ཐོ།',
  'sign-out': 'ཕྱིར་འཐེན།',
  'very-small': 'དཔེ་ཆུང་ཆུང་།',
  'small': 'ཆུང་ཆུང་།',
  'medium': 'འབྲིང་པོ།',
  'large': 'ཆེན་པོ།',
  'very-large': 'དཔེ་ཆེུན་པོ།',
  'interface-font-size': 'འཕྲད་ངོས་ཡི་གེ་ཆེ་ཆུང་།',
  'about': 'སྐོར།',
  'add-a-folder': 'ཡིག་སྒྲོམ་ཞིག་སྣོན།',
  'add-entry': 'ཚིག་ཚན།',
  'add-folder': 'ཡིག་སྒྲོམ་སྣོན།',
  'app-language': 'སྐད་ཡིག །',
  'app-font': 'ཡི་གེ།',
  'back': 'ཕྱིར་ལྡོག །',
  'bo': 'བོད་སྐད།',
  'cancel': 'སུབས།',
  'category': 'ཁོངས་གཏོགས།',
  'category-1': 'མི།',
  'category-2': 'ལྷ།',
  'category-3': 'གཙུག་ལག་ཁང་།',
  'category-4': 'གཞི།',
  'category-5': 'གཞུང་།',
  'category-6': 'དངོས་པོ།',
  'category-7': 'གྲངས།',
  'category-8': 'མིང་ཚིག །',
  'choose-at-least-one-content-field': 'གཤམ་གསལ་གྲལ་ཕྲེང་ཞིག་གདམ་རོགས།',
  'choose-at-least-one-target-language': 'སྐད་ཡིག་གདམ་རོགས།',
  'choose-csv-file': 'CSV ཡིག་ཆ་གདམ།',
  'clear-filter': 'ཡིག་ཚགས་བྱེད།',
  'completed-csv-line': '{completedLines} བསྒྲུབས་ཟིན་པའི་ཀ་ཐིག །',
  'confirm': 'གཏན་འཁེལ།',
  'content-fields': 'ཀ་ཐིག་ནང་དོན།',
  'csv-imported-done': '{filename} འཕྲུལ་འཇུག་ཟིན།',
  'delete': 'སུབས།',
  'delete-folder-instruction': '{folderName} འཕྲུལ་འཇུག་འདི་སུབ་ཟིན་ན། བསྐྱར་ལོག་མི་ཐུབ་པས་དགོངས་འཇག་ཞུ།',
  'done': 'བྱས་ཟིན།',
  'edit': 'ཕྱོགས་སྒྲིག །',
  'edit-folder': 'ཡིག་སྒྲོམ་ཕྱོགས་སྒྲིག །',
  'edit-folder-entry': '{sourceEntry} ཕྱོགས་སྒྲིག །',
  'en': 'དབྱིན་ཇི།',
  'explaination': 'གསལ་བཤད།',
  'explaination-category-1': 'ཁྱད་ཆོས།',
  'explaination-category-10': 'ཁྱབ་བྱེད།',
  'explaination-category-11': 'རྒྱ་གར་སྐད།',
  'explaination-category-12': 'རྒྱ་ནག་སྐད།',
  'explaination-category-13': 'སོག་སྐད།',
  'explaination-category-2': 'ལྷ།',
  'explaination-category-3': 'གཙུག་ལག་ཁང་།',
  'explaination-category-4': 'གཞི།',
  'explaination-category-5': 'ཆོས་གཞུང་།',
  'explaination-category-6': 'དངོས་པོ།',
  'explaination-category-7': 'ཁྲིམས།',
  'explaination-category-8': 'མིང་ཚིག །',
  'explaination-category-9': 'སྐད་ཡིག །',
  'explaination-category-num': '{num} ཁོངས་གཏོགས་གསལ་བཤད།',
  'explaination-lang': '{lang} གསལ་བཤད།',
  'explaination-note': 'བརྗེད་ཐོ་གསལ་བཤད།',
  'explaination-note-num': '{num} བརྗེད་ཐོ་གསལ་བཤད།',
  'explaination-num-lang': '{num} - {lang} གསལ་བཤད།',
  'explaination-source-num': '{num} གསལ་བཤད་བྱུང་ཁུངས།',
  'export': 'ཕྱིར་འཐེན།',
  'field-source-language-required': 'གསལ་བཤད་བྱུང་ཁུངས་ཀྱི་སྐད་ཡིག །',
  'folder-entries': '{folderName} གྱི་ཚིག་ཚན།',
  'folder-entries-has-been-deleted': '{count} སུབ་ཟིན་གྱི་ཚིག་ཚན།',
  'folder-entry-has-been-created': '{sourceEntry} བཀོད་ཟིན་གྱི་ཚིག་ཚན།',
  'folder-entry-has-been-updated': '{sourceEntry} ཁ་གསབ་ཟིན་གྱི་ཚིག་ཚན།',
  'folder-entry-name-required': 'ནང་དོན་བཅུག་དགོས་པའི་ཚིག་ཚན།',
  'folder-entry-name-taken': 'ཡིག་སྒྲོམ་འདིར་བཅུག་ཟིན་པའི་ཚིག་ཚན།',
  'folder-has-been-created': '{folderName} ཡིག་སྒྲོམ་འདི་བཀོད་ཟིན།',
  'folder-has-been-deleted': '{folderName} ཡིག་སྒྲོམ་འདི་སུབ་ཟིན།',
  'folder-has-been-updated': '{folderName} ཡིག་སྒྲོམ་ཕྱོགས་སྒྲིག་ཟིན།',
  'folder-name': 'ཡིག་སྒྲོམ་གྱི་མིང་།',
  'folder-name-required': 'ཡིག་སྒྲོམ་གྱི་མིང་བཅུག་དགོས།',
  'folder-name-taken': '{folderName} ཡིག་སྒྲོམ་གྱི་མིང་བཅུག་ཟིན།',
  'folders': 'ཡིག་སྒྲོམ་རྣམས།',
  'garchen': 'སྒར་ཆེན་ཚིག་མཛོད་ཕྱོགས་སྒྲིག་མཉེན་ཆས།',
  'home': 'མདུན་ངོས།',
  'import-csv-file': 'CSV འཕྲུལ་འཇུག་གི་ཡིག་སྒྲོམ།',
  'import-csv-rule-1': '༡ {supportedLangs} འདི་གསར་ཐོན་འདིའི་གསང་ཡིག་རེད་དེ། གསང་ཡིག་གཞན་ {langExpression} འདི་ཡང་རེད།',
  'import-csv-rule-2': '༢ {langExpression} ཟེར་ན་སྐད་ཡིག་གི་གསང་ཡིག་ཡིན། །དཔེར་ན། ཚིག་ཚན་བྱུང་བའི་ཀ་ཐིག་ལ་ source-entry-{langExpression} ཡོད་པ་དེ་བོད་ཡིག་གདམས་ན་ source-entry-bo ལྟ་བུར་འགྱུར།',
  'import-csv-rule-3': '༣ {supportedColumnNames} ཀ་ཐིག་གི་མིང་ཡིན།',
  'import-csv-rule-4': '༤ གྲལ་དང་པོར་ཀ་ཐིག་གི་གསལ་བཤད་དགོས་པ་དང་ source-entry-[lang] ཡོད་དགོས་པས་ང་ཚོའི་དཔེ་དང་སྒོ་བསྟུན་རོགས།',
  'import-csv-rule-5': '༥ འཕྲུལ་འཇུག་གནང་བའི་སྐབས་དུས་ཡུན་འགོར་ན་སྒྲིག་སྟངས་ནང་དུ་འཕྲུལ་འཇུག་གི་དུས་ཡུན་རིང་དུ་བཏང་རོགས།',
  'login': 'ཐོ་འཇུག །',
  'matched-message': '{count} དང་མཐུན་པར་ {keyword} གྱི་གྲལ་རིམ་མམ་ཀ་ཐིག་ལ་ཚིག་ཚན་ཤར།',
  'next-page': 'རྒྱབ་ཤོག །',
  'no-column-row-detected': '{errorFilename} ཀ་ཐིག་ཏུ་མིང་ནོར་འཁྲུལ་བྱུང་འདུག །',
  'original-lang': '{lang} མ་དཔེ།',
  'page-num': 'ཤོག་གྲངས།',
  'please-input-exact-the-same-folder-name': '{folderName} བཅུག་རོགས།',
  'prev-page': 'མདུན་ཤོག །',
  'search-entries': 'ཚིག་ཚན་ཚོལ།',
  'sect': 'ཆོས་བརྒྱུད།',
  'sect-1': 'རྙིང་མ།',
  'sect-2': 'བཀའ་གདམས།',
  'sect-3': 'ས་སྐྱ།',
  'sect-4': 'བཀའ་བརྒྱུད།',
  'sect-5': 'ཤངས་པ་བཀའ་བརྒྱུད།',
  'sect-6': 'ཞི་གཅོད།',
  'sect-7': 'དུས་འཁོར།',
  'sect-8': 'བསྙེན་སྒྲུབ།',
  'see-imported-folder': 'འཕྲུལ་འཇུག་ཡིག་སྒྲོམ་དུ་གཟིགས།',
  'settings': 'སྒྲིག་སྟངས།',
  'source': 'བྱུང་བའི་ཁུངས།',
  'source-entry': 'ནས་བྱུང་བའི་ཚིག་ཚན།',
  'source-entry-lang': '{lang} ནས་བྱུང་བའི་ཚིག་ཚན།',
  'source-lang': '{lang} ནས་བྱུང་བའི་ཁུངས།',
  'source-language': 'སྐད་ཡིག་ནས་བྱུང་བའི་ཁུངས།',
  'submit': 'རྩིས་འབུལ།',
  'target-entry-lang': '{lang} ཚིག་ཚན།',
  'target-language': 'དམིགས་པའི་སྐད་ཡིག །',
  'update': 'ཁ་གསབ་བྱེད།',
  'write-delay-with-num': 'སྐད་ཅིག་ཆ་ཤས། {writeDelay} ཕྱིར་བཤོལ་དུས་ཡུན་བཅུག་རོགས།',
  'zh-CN': 'དེང་སང་རྒྱ་ནག་སྐད།',
  'zh-TW': 'མནའ་བོའི་རྒྱ་ནག་སྐད།'
};
