module.exports = {
  'delete-current-entry': 'Delete Current Entry',
  'dismiss': 'སྒོ་རྒྱག །',
  'about': 'སྐོར།',
  'about-heading': 'ངོ་སྤྲོད་དོར་བསྡུས།',
  'about-content': '<p>གར་ཆེན་ཚིག་མཛོད་ཆེན་མོའི་ཕྱོགས་སྒྲིག་ཤོད་སྟེགས་དེ་ནི།</p><p>གློག་ཀླད་ནང་ཁུང་སྐད་རིགས་མི་འདྲ་བའི་ཚིག་མཛོད་རིས་ཁོད་སྙོམས་བྱས་ནས་འཕྲད་ངོས་ནུས་པའི་མཐུན་རྐྱེན་སྦྱོར་བ་དང་། </p><p>ཕྱོགས་སྒྲིག་འཕྲད་ངོས་འདིས་ཚིག་མཛོད་ཀྱི་མིང་ཚིག་རིས། དེའི་གསལ་བཤད། བསྐུལ་ཚིག་དང་དེའི་སྡེ་ཚན་དང་མཆན་འགྲེལ་རྣམས་ནས་འཇུག</p><p>གཞན་ཡང་ཤོད་སྟེགས་འདིས་ཚིག་མཛོད་འབའ་ཞིག་གིས་མིང་ཚིག་གམ་དེའི་གསལ་བཤད་དང་མཆན་འགྲེལ་ཚོལ་ནུས།</p><p>འདི་འབད་སྤྱོད་བཏང་ཡག་ལ་སྟབས་བདེ་པོ་ཡོད། དཔེར་ན།</p><p>དུས་གཅིག་ཏུ་མིང་ཚིག་གང་ཡང་རུང་བ་ཞིག་ཚིག་མཛོད་དུ་མ་ལས་ཚོལ་ནུས་པའི་ཆ་རྐྱེན་དུ་གྱུར་པ་ཅན་ཞིག་ཡིན། </p><p>དེར་མ་ཟད་མིང་ཚིག་ཞིག་ཚིག་མཛོད་ཀྱི་སྡེ་ཚན་དུ་མ་ལས་གནང་བའི་གསལ་བཤད།</p><p>ཟུར་མཆན་རྒྱབ་ནས་གནས་གཞན་དུ་ཕྱིར་འདྲེན་སོགས་ཤོད་སྟེགས་འདི་འབད་སྤྱོད་དུ་གནང་ཐུབ། </p><p>མ་འོངས་པར་ཆ་རྐྱེན་དེ་དག་དང་ལྡན་པའི་ཤོད་སྟེགས་འདིར་གར་ཆེན་ཚིག་མཛོད་ཆེན་མོར་གུང་སྒྲིག་བྱེད་རྒྱུ་ཡིན།།</p>',
  'account': 'དྲྭ་ཐོ།',
  'add-a-folder': 'ཡིག་སྒྲོམ་ཞིག་སྣོན།',
  'add-entry': 'ཚིག་ཚན།',
  'add-folder': 'ཡིག་སྒྲོམ་སྣོན།',
  'app-font': 'ཡི་གེ།',
  'app-language': 'སྐད་ཡིག །',
  'back': 'ཕྱིར་ལྡོག །',
  'bo': 'བོད་སྐད།',
  'cancel': 'སུབས།',
  'cancel-importing': 'སུབས་ཤིག །',
  'category': 'ཁོངས་གཏོགས།',
  'category-1': 'མི།',
  'category-2': 'ལྷ།',
  'category-3': 'གཙུག་ལག་ཁང་།',
  'category-4': 'གཞི།',
  'category-5': 'གཞུང་།',
  'category-6': 'དངོས་པོ།',
  'category-7': 'གྲངས།',
  'category-8': 'མིང་ཚིག །',
  'choose-at-least-one-content-field': 'གཤམ་གསལ་གྲལ་ཕྲེང་ཞིག་གདམ་རོགས།',
  'choose-at-least-one-target-language': 'སྐད་ཡིག་གདམ་རོགས།',
  'choose-csv-file': 'CSV ཡིག་ཆ་གདམ།',
  'clear-filter': 'ཡིག་ཚགས་བྱེད།',
  'clear-recycle-bin': 'སྙིགས་སྒམ་གཙང་སེལ།',
  'completed-csv-line': '{completedLines} བསྒྲུབས་ཟིན་པའི་ཀ་ཐིག །',
  'confirm': 'གཏན་འཁེལ།',
  'content-confirm-delete-dialog1': 'ཚིག་འདི་དག་བསུབ་པར་བྱའམ།',
  'content-confirm-delete-dialog2': 'ཚིག་ཆན་འདི་དག་བསུབས་ན་ལོག་མི་ཐུབ་པས་ཟབ་ཟབ་གནང་།',
  'content-confirm-recycle-bin-dialog1': 'སྙིགས་སྒམ་གཙང་སེལ་བྱའམ།',
  'content-confirm-recycle-bin-dialog2': 'བྱ་སྤྱོད་འདི་སླར་གསོ་མི་ཐུབ།',
  'content-fields': 'ཀ་ཐིག་ནང་དོན།',
  'cross-folder-search': 'ཀུ་རུ་ཁའི་རྟགས་ཅན་ཡིག་སྒྲོམ་ཚོལ།',
  'csv-imported-done': '{filename} འཕྲུལ་འཇུག་ཟིན།',
  'delete': 'སུབས།',
  'delete-folder-instruction': '{folderName} འཕྲུལ་འཇུག་འདི་སུབ་ཟིན་ན། བསྐྱར་ལོག་མི་ཐུབ་པས་དགོངས་འཇག་ཞུ།',
  'delete-selected-folders': 'གདམ་ག་ཅན་ཡིག་སྒྲོམ་སུབ།',
  'deleted-at': 'སུབ་པའི་དུས།',
  'display-deleted-folder-perpage': 'ཡིག་སྒྲོམ་ {perpage} ཤོག་ལྡེབ་རེར་བཀོད། (སྙིགས་སྒམ)',
  'display-entry-perpage': 'ཚིག་ཚན་ {perpage} ཤོག་ལྡེབ་རེར་བཀོད།',
  'display-folder-perpage': 'ཡིག་སྒྲོམ་ {perpage} ཤོག་ལྡེབ་རེར་བཀོད།',
  'done': 'བྱས་ཟིན།',
  'edit': 'ཕྱོགས་སྒྲིག །',
  'edit-folder': 'ཡིག་སྒྲོམ་ཕྱོགས་སྒྲིག །',
  'edit-folder-entry': '{sourceEntry} ཕྱོགས་སྒྲིག །',
  'empty-recycle-bin': 'སྙིགས་སྒམ་ཁོང་སྟོང་།',
  'en': 'དབྱིན་ཇི།',
  'explanation': 'གསལ་བཤད།',
  'explanation-category-1': 'ཁྱད་ཆོས།',
  'explanation-category-10': 'ཁྱབ་བྱེད།',
  'explanation-category-11': 'རྒྱ་གར་སྐད།',
  'explanation-category-12': 'རྒྱ་ནག་སྐད།',
  'explanation-category-13': 'སོག་སྐད།',
  'explanation-category-2': 'ལྷ།',
  'explanation-category-3': 'གཙུག་ལག་ཁང་།',
  'explanation-category-4': 'གཞི།',
  'explanation-category-5': 'ཆོས་གཞུང་།',
  'explanation-category-6': 'དངོས་པོ།',
  'explanation-category-7': 'ཁྲིམས།',
  'explanation-category-8': 'མིང་ཚིག །',
  'explanation-category-9': 'སྐད་ཡིག །',
  'explanation-category-num': '{num} ཁོངས་གཏོགས་གསལ་བཤད།',
  'explanation-lang': '{lang} གསལ་བཤད།',
  'explanation-note': 'བརྗེད་ཐོ་གསལ་བཤད།',
  'explanation-note-num': '{num} བརྗེད་ཐོ་གསལ་བཤད།',
  'explanation-num-lang': '{num} - {lang} གསལ་བཤད།',
  'explanation-source-num': '{num} གསལ་བཤད་བྱུང་ཁུངས།',
  'export': 'ཕྱིར་འཐེན།',
  'field-source-language-required': 'གསལ་བཤད་བྱུང་ཁུངས་ཀྱི་སྐད་ཡིག །',
  'folder-entries': '{folderName} གྱི་ཚིག་ཚན།',
  'folder-entries-has-been-deleted': '{count} སུབ་ཟིན་གྱི་ཚིག་ཚན།',
  'folder-entry-has-been-created': '{sourceEntry} བཀོད་ཟིན་གྱི་ཚིག་ཚན།',
  'folder-entry-has-been-updated': '{sourceEntry} ཁ་གསབ་ཟིན་གྱི་ཚིག་ཚན།',
  'folder-entry-name-required': 'ནང་དོན་བཅུག་དགོས་པའི་ཚིག་ཚན།',
  'folder-entry-name-taken': 'ཡིག་སྒྲོམ་འདིར་བཅུག་ཟིན་པའི་ཚིག་ཚན།',
  'folder-has-been-created': '{folderName} ཡིག་སྒྲོམ་འདི་བཀོད་ཟིན།',
  'folder-has-been-updated': '{folderName} ཡིག་སྒྲོམ་ཕྱོགས་སྒྲིག་ཟིན།',
  'folder-has-been-exported': '{folderName} ཡིག་སྒྲོམ་ཕྱིར་འཐེན་ཟིན།',
  'folder-name': 'ཡིག་སྒྲོམ་གྱི་མིང་།',
  'folder-name-required': 'ཡིག་སྒྲོམ་གྱི་མིང་བཅུག་དགོས།',
  'folder-name-taken': '{folderName} ཡིག་སྒྲོམ་གྱི་མིང་བཅུག་ཟིན།',
  'folders': 'ཡིག་སྒྲོམ་རྣམས།',
  'folders-have-been-deleted': 'ཡིག་སྒྲོམ་འདི་སུབ་ཟིན།',
  'folders-have-been-restored': 'ཡིག་སྒྲོམ་སོར་ཆུད་བྱས་ཚར།',
  'garchen': 'སྒར་ཆེན་ཚིག་མཛོད་ཕྱོགས་སྒྲིག་མཉེན་ཆས།',
  'home': 'མདུན་ངོས།',
  'import-csv-file': 'CSV འཕྲུལ་འཇུག་གི་ཡིག་སྒྲོམ།',
  'import-csv-rule-1': '༡ {supportedLangs} འདི་གསར་ཐོན་འདིའི་གསང་ཡིག་རེད་དེ། གསང་ཡིག་གཞན་ {langExpression} འདི་ཡང་རེད།',
  'import-csv-rule-2': '༢ {langExpression} ཟེར་ན་སྐད་ཡིག་གི་གསང་ཡིག་ཡིན། །དཔེར་ན། ཚིག་ཚན་བྱུང་བའི་ཀ་ཐིག་ལ་ source-entry-{langExpression} ཡོད་པ་དེ་བོད་ཡིག་གདམས་ན་ source-entry-bo ལྟ་བུར་འགྱུར།',
  'import-csv-rule-3': '༣ {supportedColumnNames} ཀ་ཐིག་གི་མིང་ཡིན།',
  'import-csv-rule-4': '༤ གྲལ་དང་པོར་ཀ་ཐིག་གི་གསལ་བཤད་དགོས་པ་དང་ source-entry-[lang] ཡོད་དགོས་པས་ང་ཚོའི་དཔེ་དང་སྒོ་བསྟུན་རོགས།',
  'large': 'ཆེན་པོ།',
  'login': 'ཐོ་འཇུག །',
  'matched-message': '{count} དང་མཐུན་པར་ {keyword} གྱི་གྲལ་རིམ་མམ་ཀ་ཐིག་ལ་ཚིག་ཚན་ཤར།',
  'medium': 'འབྲིང་པོ།',
  'next-page': 'རྒྱབ་ཤོག །',
  'no-column-row-detected': '{errorFilename} ཀ་ཐིག་ཏུ་མིང་ནོར་འཁྲུལ་བྱུང་འདུག །',
  'original-lang': '{lang} མ་དཔེ།',
  'original': 'མ་དཔེ།',
  'page-num': 'ཤོག་གྲངས།',
  'please-input-exact-the-same-folder-name': '{folderName} བཅུག་རོགས།',
  'prev-page': 'མདུན་ཤོག །',
  'recycle-bin': 'སྙིགས་སྒམ།',
  'restore': 'སོར་ཆུད།',
  'search-entries': 'ཚིག་ཚན་ཚོལ།',
  'sect': 'ཆོས་བརྒྱུད།',
  'sect-1': 'རྙིང་མ།',
  'sect-2': 'བཀའ་གདམས།',
  'sect-3': 'ས་སྐྱ།',
  'sect-4': 'བཀའ་བརྒྱུད།',
  'sect-5': 'ཤངས་པ་བཀའ་བརྒྱུད།',
  'sect-6': 'ཞི་གཅོད།',
  'sect-7': 'དུས་འཁོར།',
  'sect-8': 'བསྙེན་སྒྲུབ།',
  'see-imported-folder': 'འཕྲུལ་འཇུག་ཡིག་སྒྲོམ་དུ་གཟིགས།',
  'settings': 'སྒྲིག་སྟངས།',
  'sign-out': 'ཕྱིར་འཐེན།',
  'small': 'ཆུང་ཆུང་།',
  'source': 'བྱུང་བའི་ཁུངས།',
  'source-entry': 'ནས་བྱུང་བའི་ཚིག་ཚན།',
  'source-entry-lang': '{lang} ནས་བྱུང་བའི་ཚིག་ཚན།',
  'source-lang': '{lang} ནས་བྱུང་བའི་ཁུངས།',
  'source-language': 'སྐད་ཡིག་ནས་བྱུང་བའི་ཁུངས།',
  'submit': 'རྩིས་འབུལ།',
  'target-entry-lang': '{lang} ཚིག་ཚན།',
  'target-entry': 'ཚིག་ཚན།',
  'target-language': 'དམིགས་པའི་སྐད་ཡིག །',
  'title-confirm-clear-recycle-bin-dialog': 'སྙིགས་སྒམ་གཙང་སེལ་གཏན་འབེབས་གནང་།',
  'title-confirm-delete-dialog': 'ཚིག་སུབ་པའི་གཏན་འབེབས་གནང་།',
  'update': 'ཁ་གསབ་བྱེད།',
  'very-large': 'དཔེ་ཆེུན་པོ།',
  'very-small': 'དཔེ་ཆུང་ཆུང་།',
  'write-delay-with-num': 'སྐད་ཅིག་ཆ་ཤས། {writeDelay} ཕྱིར་བཤོལ་དུས་ཡུན་བཅུག་རོགས།',
  'zh-CN': 'དེང་སང་རྒྱ་ནག་སྐད།',
  'zh-TW': 'མནའ་བོའི་རྒྱ་ནག་སྐད།'
};
