module.exports = {
  'cancel': 'Cancel',
  'submit': 'Submit',
  'export': 'Export',
  'folder-has-been-deleted': 'Folder {folderName} has been deleted.',
  'please-input-exact-the-same-folder-name': 'Please input {folderName}',
  'delete': 'delete',
  'delete-folder-instruction': 'Input {folderName} to delete this folder, once you delete a repository, there is no going back. Please be certain.',
  'add-entry': 'Add entry',
  'folder-entries': 'Folder {folderName}\'s entries',
  'field-source-language-required': 'Field source language is required.',
  'choose-at-least-one-target-language': 'Please choose at least one target language.',
  'choose-at-least-one-content-field': 'Please choose at least one content field.',
  'folder-name-taken': 'Folder name {folderName} exists',
  'folder-name-required': 'Field folder name is required.',
  'back': 'Back',
  'next-page': 'Next',
  'prev-page': 'Prev',
  'folder-has-been-updated': 'Folder {folderName} has been updated.',
  'folder-has-been-created': 'Folder {folderName} has been created.',
  'update': 'Update',
  'edit-folder': 'Edit Folder',
  'edit': 'Edit',
  'add-folder': 'Add Folder',
  'en': 'English',
  'zh-TW': 'Traditial Chinese',
  'zh-CN': 'Simplified Chinese',
  'bo': 'Tibetan',
  'garchen': 'Garchen',
  'settings': 'Settings',
  'app-language': 'App Language',
  'home': 'Home',
  'folders': 'Folders',
  'about': 'About',
  'login': 'Login',
  'folder-name': 'Folder Name',
  'source-language': 'Source Language',
  'target-language': 'Target Language',
  'target-entry-lang': 'Entry - {lang}',
  'category': 'Category',
  'sect': 'Sect',
  'explaination-lang': 'Explaination - {lang}',
  'original-lang': 'Original - {lang}',
  'source-lang': 'Source - {lang}',
  'content-fields': 'Content Fields'
};
