module.exports = {
  'about': 'About',
  'add-a-folder': 'Add a folder',
  'add-entry': 'Add Entry',
  'add-folder': 'Add Folder',
  'app-language': 'App Language',
  'back': 'Back',
  'bo': 'Tibetan',
  'cancel': 'Cancel',
  'category': 'Category',
  'category-1': 'People',
  'category-2': 'Repect',
  'category-3': 'Temple',
  'category-4': 'Ground',
  'category-5': 'Sutra',
  'category-6': 'Thing',
  'category-7': 'Amount',
  'category-8': 'Sentence',
  'choose-at-least-one-content-field': 'Please choose at least one content field.',
  'choose-at-least-one-target-language': 'Please choose at least one target language.',
  'choose-csv-file': 'Choose CSV file',
  'clear-filter': 'Clear filter',
  'completed-csv-line': 'Completed {completedLines} lines',
  'confirm': 'Confirm',
  'content-fields': 'Content Fields',
  'csv-imported-done': '{filename} has been imported',
  'delete': 'delete',
  'delete-folder-instruction': 'Input {folderName} to delete this folder, once you delete a repository, there is no going back. Please be certain.',
  'done': 'Done',
  'edit': 'Edit',
  'edit-folder': 'Edit Folder',
  'edit-folder-entry': 'Edit {sourceEntry}',
  'en': 'English',
  'explaination': 'Explaintion',
  'explaination-category-1': 'Character',
  'explaination-category-10': 'Term',
  'explaination-category-11': 'Sanskrit',
  'explaination-category-12': 'Chinese',
  'explaination-category-13': 'Mongolian',
  'explaination-category-2': 'Gods',
  'explaination-category-3': 'Temple',
  'explaination-category-4': 'Location',
  'explaination-category-5': 'Classic',
  'explaination-category-6': 'Item',
  'explaination-category-7': 'Law',
  'explaination-category-8': 'Sentence',
  'explaination-category-9': 'Language',
  'explaination-category-num': 'Explaination Category {num}',
  'explaination-lang': 'Explaination - {lang}',
  'explaination-note': 'Explaination Note',
  'explaination-note-num': 'Explaination Note {num}',
  'explaination-num-lang': 'Explaination {num} - {lang}',
  'explaination-source-num': 'Explaination Source {num}',
  'export': 'Export',
  'field-source-language-required': 'Field source language is required.',
  'folder-entries': '{folderName} 的詞條',
  'folder-entries-has-been-deleted': 'Deleted {count} entries.',
  'folder-entry-has-been-created': 'Entry {sourceEntry} has been created.',
  'folder-entry-has-been-updated': 'Entry {sourceEntry} has been updated.',
  'folder-entry-name-required': 'Entry field is required.',
  'folder-entry-name-taken': 'Entry already existed in this folder.',
  'folder-has-been-created': 'Folder {folderName} has been created.',
  'folder-has-been-deleted': 'Folder {folderName} has been deleted.',
  'folder-has-been-updated': 'Folder {folderName} has been updated.',
  'folder-name': 'Folder Name',
  'folder-name-required': 'Field folder name is required.',
  'folder-name-taken': 'Folder name {folderName} exists',
  'folders': 'Folders',
  'garchen': 'Garchen',
  'home': 'Home',
  'import-csv-file': 'Import CSV file',
  'import-csv-rule-1': '1. Supported language codes are {supportedLangs} in this version, also known as {langExpression}',
  'import-csv-rule-2': '2. {langExpression} means the language code that supposed to be matched. For example, the column name of Source Entry is `source-entry-{langExpression}`.  It becomes source-entry-bo when Tibetan language code is applied.',
  'import-csv-rule-3': '3. Supported column names are {supportedColumnNames}.',
  'import-csv-rule-4': '4. First row should have column definition and MUST have source-entry-[lang], Please refer to our example file ',
  'import-csv-rule-5': '5. Please increase the write delay in settings page if you experience any slow responses while importing.',
  'login': 'Login',
  'matched-message': '{count} results for entries matching {keyword}',
  'next-page': 'Next',
  'no-column-row-detected': '在 {errorFilename} 偵測不到欄位資訊',
  'original-lang': 'Original - {lang}',
  'page-num': 'Page Number',
  'please-input-exact-the-same-folder-name': 'Please input {folderName}',
  'prev-page': 'Prev',
  'search-entries': 'Search entries...',
  'sect': 'Sect',
  'sect-1': 'Old',
  'sect-2': 'When',
  'sect-3': 'Sa',
  'sect-4': 'Karma',
  'sect-5': 'Fragant',
  'sect-6': 'Time',
  'sect-7': 'Off',
  'sect-8': 'According',
  'see-imported-folder': 'See imported folder',
  'settings': 'Settings',
  'source': 'Source',
  'source-entry': 'Source Entry',
  'source-entry-lang': 'Source Entry - {lang}',
  'source-lang': 'Source - {lang}',
  'source-language': 'Source Language',
  'submit': 'Submit',
  'target-entry-lang': 'Entry - {lang}',
  'target-language': 'Target Language',
  'update': 'Update',
  'write-delay-with-num': 'Write delay {writeDelay}ms',
  'zh-CN': 'Simplified Chinese',
  'zh-TW': 'Traditial Chinese'
};
