module.exports = {
  'other-fields': '其他字段',
  'delete-current-entry': '删除当前词条',
  'modal-delete-entry-content': '你确定要删除当前词条吗?',
  'modal-delete-entry-title': '删除当前词条',
  'dismiss': '关闭',
  'delete-selected-folders': '删除所选的资料夹',
  'about': '关于',
  'about-heading': '关于 Garchen Panel',
  'about-content': '<p>噶千词典编辑平台是一套集成多国语系介面的词典编辑工具。</p><p>借由这个编辑平台，使用者可以编辑词条、解释、分类及注记。并且可以搜寻词条，阅读词条内容与解释。</p><p>使用者可以将词条做不同解释的资料分类，也可以加上注记、出处。未来我们将利用这套编辑平台进行噶千词典的编撰整理。</p><p>这套编辑平台也是一套方便使用的电子词典资料库，我们可以进行一个或多个字典资料库的搜寻。</p><hr/><p><table width="100%"><tr align="center"><td><a href="https://youtu.be/xzEkK07CbSc" target="_blank">介绍影片</a><br><iframe width="400px" height="225px" src="https://www.youtube.com/embed/xzEkK07CbSc?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></td><td><a href="https://youtu.be/4yf-wq147Po" target="_blank">使用教学</a><br/><iframe width="400" height="225" src="https://www.youtube.com/embed/4yf-wq147Po" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></td></tr></table></p>',
  'account': '帐号',
  'add-a-folder': '新增一个资料夹',
  'add-entry': '新增词条',
  'add-folder': '新增资料夹',
  'app-font': '应用程式字型',
  'app-language': '应用程式语言',
  'back': '上一页',
  'bo': '藏文',
  'cancel': '取消',
  'cancel-importing': '取消汇入',
  'category': '类別',
  'category-1': '人',
  'category-2': '尊',
  'category-3': '寺',
  'category-4': '地',
  'category-5': '经',
  'category-6': '物',
  'category-7': '量',
  'category-8': '句',
  'choose-at-least-one-content-field': '请至少选择一个内容字段',
  'choose-at-least-one-target-language': '请至少选择一个目标语言',
  'choose-csv-file': '选择 CSV 档案',
  'clear-filter': '清除关键字',
  'clear-recycle-bin': '清除资源回收桶',
  'completed-csv-line': '已写入 {completedLines} 行',
  'confirm': '确认',
  'content-confirm-delete-dialog1': '你确定要删除这些词条吗?',
  'content-confirm-delete-dialog2': '一旦词条被删除后, 被删除的资料将没有办法复原, 请谨慎操作',
  'content-confirm-recycle-bin-dialog1': '你确定你要清除资源回收桶吗?',
  'content-confirm-recycle-bin-dialog2': '被清除的资料将无法复原',
  'content-fields': '内容字段',
  'cross-folder-search': '跨资料夹搜寻',
  'csv-imported-done': '{filename} 已汇入完成',
  'delete': '删除',
  'delete-folder-instruction': '输入 {folderName} 删除这个资料夹, 被删除的资料将没办法复原',
  'deleted-at': '删除时间',
  'display-deleted-folder-perpage': '一页显示 {perpage} 个资料夹 (资源回收桶)',
  'display-entry-perpage': '一页显示 {perpage} 个词条',
  'display-folder-perpage': '一页显示 {perpage} 个资料夹',
  'done': '完成',
  'edit': '编辑',
  'edit-folder': '编辑资料夹',
  'edit-folder-entry': '编辑 {sourceEntry}',
  'empty-recycle-bin': '清除資源回收桶',
  'en': '英文',
  'explanation': '解释',
  'explanation-category-1': '人物',
  'explanation-category-10': '术语',
  'explanation-category-11': '梵语',
  'explanation-category-12': '汉语',
  'explanation-category-13': '蒙古语',
  'explanation-category-2': '神尊',
  'explanation-category-3': '寺庙',
  'explanation-category-4': '地方',
  'explanation-category-5': '经典',
  'explanation-category-6': '物品',
  'explanation-category-7': '法数',
  'explanation-category-8': '文句',
  'explanation-category-9': '语言',
  'explanation-category-num': '解释分类 {num}',
  'explanation-lang': '解释 - {lang}',
  'explanation-note': '解释注解',
  'explanation-note-num': '解释注记 {num}',
  'explanation-num-lang': '解释 {num} - {lang}',
  'explanation-source-num': '解释出处 {num}',
  'export': '汇出',
  'field-source-language-required': '必须填写来源语言',
  'folder-entries': '{folderName} 的词条',
  'folder-entries-has-been-deleted': '已删除 {count} 个词条',
  'folder-entry-has-been-created': '已新增词条 {sourceEntry}',
  'folder-entry-has-been-updated': '已更新词条 {sourceEntry}',
  'folder-entry-name-required': '必须填写词条',
  'folder-entry-name-taken': '词条在这个资料夹已经存在',
  'folder-has-been-created': '已建立资料夹 {folderName}',
  'folder-has-been-updated': '已更新资料夹 {folderName}',
  'folder-has-been-exported': '已汇出资料夹 {folderName}',
  'folder-name': '资料夹名称',
  'folder-name-required': '必须填写资料夹名称',
  'folder-name-taken': '资料夹名称 {folderName} 已经存在',
  'folders': '资料夹列表',
  'folders-have-been-deleted': '已删除资料夹',
  'folders-have-been-restored': '資料夾已复原',
  'garchen': '噶千大词典编辑平台',
  'home': '首页',
  'import-csv-file': '汇入 CSV 档案',
  'import-csv-rule-1': '1. 本版本支援的字典语言代码有: {supportedLangs}, 以下简称 {langExpression}',
  'import-csv-rule-2': '2. 以下有用到多国语言的字段名称以 {langExpression} 表示对应的语言代码, 例如主词条的字段 source-entry-{langExpression} 套用藏文后变为 source-entry-bo',
  'import-csv-rule-3': '3. 支援的字段名称有: {supportedColumnNames}',
  'import-csv-rule-4': '4. 第一行必须定义字段, 而且必须包含一个主词条 source-entry-[lang], 范例档案请参考',
  'large': '大',
  'login': '登入',
  'matched-message': '有 {count} 个结果符合关键字 {keyword}',
  'medium': '中',
  'next-page': '下一页',
  'no-column-row-detected': '在 {errorFilename} 侦测不到字段资讯',
  'original-lang': '原文 - {lang}',
  'original': '原文',
  'page-num': '页码',
  'please-input-exact-the-same-folder-name': '请输入{folderName}',
  'prev-page': '上一页',
  'recycle-bin': '资源回收桶',
  'restore': '复原',
  'search-entries': '搜寻词条...',
  'sect': '宗派',
  'sect-1': '旧',
  'sect-2': '当',
  'sect-3': '萨',
  'sect-4': '噶',
  'sect-5': '香',
  'sect-6': '断',
  'sect-7': '时',
  'sect-8': '依',
  'see-imported-folder': '看看新汇入的资料夹',
  'settings': '设定',
  'sign-out': '登出',
  'small': '小',
  'source': '出处',
  'source-entry': '主词条',
  'source-entry-lang': '主词条 - {lang}',
  'source-lang': '出处 - {lang}',
  'source-language': '来源语言',
  'submit': '送出',
  'target-entry-lang': '词条 - {lang}',
  'target-entry': '词条',
  'target-language': '目标语言',
  'title-confirm-clear-recycle-bin-dialog': '确认清除资源回收桶',
  'title-confirm-delete-dialog': '确认删除词条',
  'update': '更新',
  'very-large': '非常大',
  'very-small': '非常小',
  'write-delay-with-num': '写入延迟时间 {writeDelay} 毫秒',
  'zh-CN': '简体中文',
  'zh-TW': '繁体中文'
};
