module.exports = {
  'about-version': '关于版本 {appVersion}',
  'content-font-size': '内文字体大小',
  'cancel-importing': '取消汇入',
  'account': '帐号',
  'sign-out': '登出',
  'very-small': '非常小',
  'small': '小',
  'medium': '中',
  'large': '大',
  'very-large': '非常大',
  'interface-font-size': '介面字体大小',
  'about': '关于',
  'add-a-folder': '新增一个资料夹',
  'add-entry': '新增词条',
  'add-folder': '新增资料夹',
  'app-language': '应用程式语言',
  'app-font': '应用程式字型',
  'back': '上一页',
  'bo': '藏文',
  'cancel': '取消',
  'category': '类別',
  'category-1': '人',
  'category-2': '尊',
  'category-3': '寺',
  'category-4': '地',
  'category-5': '经',
  'category-6': '物',
  'category-7': '量',
  'category-8': '句',
  'choose-at-least-one-content-field': '请至少选择一个内容字段',
  'choose-at-least-one-target-language': '请至少选择一个目标语言',
  'choose-csv-file': '选择 CSV 档案',
  'clear-filter': '清除关键字',
  'completed-csv-line': '已写入 {completedLines} 行',
  'confirm': '确认',
  'content-fields': '内容字段',
  'csv-imported-done': '{filename} 已汇入完成',
  'delete': '删除',
  'delete-folder-instruction': '输入 {folderName} 删除这个资料夹, 被删除的资料将没办法复原',
  'done': '完成',
  'edit': '编辑',
  'edit-folder': '编辑资料夹',
  'edit-folder-entry': '编辑 {sourceEntry}',
  'en': '英文',
  'explaination': '解释',
  'explaination-category-1': '人物',
  'explaination-category-10': '术语',
  'explaination-category-11': '梵语',
  'explaination-category-12': '汉语',
  'explaination-category-13': '蒙古语',
  'explaination-category-2': '神尊',
  'explaination-category-3': '寺庙',
  'explaination-category-4': '地方',
  'explaination-category-5': '经典',
  'explaination-category-6': '物品',
  'explaination-category-7': '法数',
  'explaination-category-8': '文句',
  'explaination-category-9': '语言',
  'explaination-category-num': '解释分类 {num}',
  'explaination-lang': '解释 - {lang}',
  'explaination-note': '解释注解',
  'explaination-note-num': '解释注记 {num}',
  'explaination-num-lang': '解释 {num} - {lang}',
  'explaination-source-num': '解释出处 {num}',
  'export': '汇出',
  'field-source-language-required': '必须填写来源语言',
  'folder-entries': '{folderName} 的词条',
  'folder-entries-has-been-deleted': '已删除 {count} 个词条',
  'folder-entry-has-been-created': '已新增词条 {sourceEntry}',
  'folder-entry-has-been-updated': '已更新词条 {sourceEntry}',
  'folder-entry-name-required': '必须填写词条',
  'folder-entry-name-taken': '词条在这个资料夹已经存在',
  'folder-has-been-created': '已建立资料夹 {folderName}',
  'folder-has-been-deleted': '已删除资料夹 {folderName}',
  'folder-has-been-updated': '已更新资料夹 {folderName}',
  'folder-name': '资料夹名称',
  'folder-name-required': '必须填写资料夹名称',
  'folder-name-taken': '资料夹名称 {folderName} 已经存在',
  'folders': '资料夹列表',
  'garchen': '噶千大词典编辑平台',
  'home': '首页',
  'import-csv-file': '汇入 CSV 档案',
  'import-csv-rule-1': '1. 本版本支援的字典语言代码有: {supportedLangs}, 以下简称 {langExpression}',
  'import-csv-rule-2': '2. 以下有用到多国语言的字段名称以 {langExpression} 表示对应的语言代码, 例如主词条的字段 source-entry-{langExpression} 套用藏文后变为 source-entry-bo',
  'import-csv-rule-3': '3. 支援的字段名称有: {supportedColumnNames}',
  'import-csv-rule-4': '4. 第一行必须定义字段, 而且必须包含一个主词条 source-entry-[lang], 范例档案请参考',
  'import-csv-rule-5': '5. 如果觉得汇入期间操作会不顺畅可以尝试把设定页的写入延迟加长',
  'login': '登入',
  'matched-message': '有 {count} 个结果符合关键字 {keyword}',
  'next-page': '下一页',
  'no-column-row-detected': '在 {errorFilename} 侦测不到字段资讯',
  'original-lang': '原文 - {lang}',
  'page-num': '页码',
  'please-input-exact-the-same-folder-name': '请输入{folderName}',
  'prev-page': '上一页',
  'search-entries': '搜寻词条...',
  'sect': '宗派',
  'sect-1': '旧',
  'sect-2': '当',
  'sect-3': '萨',
  'sect-4': '噶',
  'sect-5': '香',
  'sect-6': '断',
  'sect-7': '时',
  'sect-8': '依',
  'see-imported-folder': '看看新汇入的资料夹',
  'settings': '设定',
  'source': '出处',
  'source-entry': '主词条',
  'source-entry-lang': '主词条 - {lang}',
  'source-lang': '出处 - {lang}',
  'source-language': '来源语言',
  'submit': '送出',
  'target-entry-lang': '词条 - {lang}',
  'target-language': '目标语言',
  'update': '更新',
  'write-delay-with-num': '写入延迟时间 {writeDelay} 毫秒',
  'zh-CN': '简体中文',
  'zh-TW': '繁体中文'
};
