module.exports = {
  'please-input-exact-the-same-folder-name': '请输入{folderName}',
  'delete': '删除',
  'delete-folder-instruction': '输入 {folderName} 删除这个资料夹, 被删除的资料将没办法复原',
  'add-entry': '新增詞條',
  'folder-entries': '資料夾 {folderName} 的詞條',
  'field-source-language-required': '必须填写来源语言',
  'choose-at-least-one-target-language': '请至少选择一个目标语言',
  'choose-at-least-one-content-field': '请至少选择一个内容栏位',
  'folder-name-taken': '资料夹名称 {folderName} 已经存在',
  'folder-name-required': '必须填写資料夾名稱',
  'back': '上一页',
  'next-page': '下一页',
  'prev-page': '上一页',
  'folder-has-been-updated': '已更新资料夹 {folderName}',
  'folder-has-been-created': '已建立资料夹 {folderName}',
  'update': '更新',
  'edit-folder': '编辑资料夹',
  'edit': '编辑',
  'add-folder': '新增资料夹',
  'en': '英文',
  'zh-TW': '繁体中文',
  'zh-CN': '简体中文',
  'bo': '藏文',
  'garchen': '噶千',
  'settings': '设定',
  'app-language': '应用程式语言',
  'home': '首页',
  'folders': '资料夹',
  'about': '关于',
  'login': '登入',
  'folder-name': '资料夹名称',
  'source-language': '来源语言',
  'target-language': '目标语言',
  'targt-entry-lang': '词条 - {lang}',
  'category': '类别',
  'sect': '宗派',
  'explaination-lang': '解释 - {lang}',
  'original-lang': '原文 - {lang}',
  'source-lang': '出处 - {lang}',
  'content-fields': '内容栏位'
};
