module.exports = {
  'about': '關於',
  'about-version': '關於版本 {appVersion}',
  'account': '帳號',
  'add-a-folder': '新增一個資料夾',
  'add-entry': '新增詞條',
  'add-folder': '新增資料夾',
  'app-font': '應用程式字型',
  'app-language': '應用程式語言',
  'back': '上一頁',
  'bo': '藏文',
  'cancel': '取消',
  'cancel-importing': '取消匯入',
  'category': '類別',
  'category-1': '人',
  'category-2': '尊',
  'category-3': '寺',
  'category-4': '地',
  'category-5': '經',
  'category-6': '物',
  'category-7': '量',
  'category-8': '句',
  'choose-at-least-one-content-field': '請至少選擇一個內容欄位',
  'choose-at-least-one-target-language': '請至少選擇一個目標語言',
  'choose-csv-file': '選擇 CSV 檔案',
  'clear-filter': '清除關鍵字',
  'clear-recycle-bin': '清除資源回收桶',
  'completed-csv-line': '已寫入 {completedLines} 行',
  'confirm': '確認',
  'content-confirm-delete-dialog1': '你確定要刪除這些詞條嗎?',
  'content-confirm-delete-dialog2': '一旦詞條被刪除後, 被刪除的資料將沒有辦法復原, 請謹慎操作',
  'content-confirm-recycle-bin-dialog1': '你確定你要清除資源回收桶嗎?',
  'content-confirm-recycle-bin-dialog2': '被清除的資料將無法復原',
  'content-fields': '內容欄位',
  'content-font-size': '內文字體大小',
  'cross-folder-search': '跨資料夾搜尋',
  'csv-imported-done': '{filename} 已匯入完成',
  'delete': '刪除',
  'delete-folder-instruction': '輸入 {folderName} 刪除這個資料夾, 被刪除的資料將沒辦法復原',
  'deleted-at': '刪除時間',
  'display-entry-perpage': '一頁顯示 {perpage} 個詞條',
  'display-folder-perpage': '一頁顯示 {perpage} 個資料夾',
  'done': '完成',
  'edit': '編輯',
  'edit-folder': '編輯資料夾',
  'edit-folder-entry': '編輯 {sourceEntry}',
  'empty-recycle-bin': '清除資源回收桶',
  'en': '英文',
  'explanation': '解釋',
  'explanation-category-1': '人物',
  'explanation-category-10': '術語',
  'explanation-category-11': '梵語',
  'explanation-category-12': '漢語',
  'explanation-category-13': '蒙古語',
  'explanation-category-2': '神尊',
  'explanation-category-3': '寺廟',
  'explanation-category-4': '地方',
  'explanation-category-5': '經典',
  'explanation-category-6': '物品',
  'explanation-category-7': '法數',
  'explanation-category-8': '文句',
  'explanation-category-9': '語言',
  'explanation-category-num': '解釋分類 {num}',
  'explanation-lang': '解釋 - {lang}',
  'explanation-note': '解釋註解',
  'explanation-note-num': '解釋註記 {num}',
  'explanation-num-lang': '解釋 {num} - {lang}',
  'explanation-source-num': '解釋出處 {num}',
  'export': '匯出',
  'field-source-language-required': '必須填寫來源語言',
  'folder-entries': '{folderName} 的詞條',
  'folder-entries-has-been-deleted': '已刪除 {count} 個詞條',
  'folder-entry-has-been-created': '已新增詞條 {sourceEntry}',
  'folder-entry-has-been-updated': '已更新詞條 {sourceEntry}',
  'folder-entry-name-required': '必須填寫詞條',
  'folder-entry-name-taken': '詞條在這個資料夾已經存在',
  'folder-has-been-created': '已建立資料夾 {folderName}',
  'folder-has-been-updated': '已更新資料夾 {folderName}',
  'folder-name': '資料夾名稱',
  'folder-name-required': '必須填寫資料夾名稱',
  'folder-name-taken': '資料夾名稱 {folderName} 已經存在',
  'folders': '資料夾列表',
  'folders-have-been-deleted': '已刪除資料夾',
  'folders-have-been-restored': '資料夾已復原',
  'garchen': '噶千大詞典編輯平台',
  'home': '首頁',
  'import-csv-file': '匯入 CSV 檔案',
  'import-csv-rule-1': '1. 本版本支援的字典語言代碼有: {supportedLangs}, 以下簡稱 {langExpression}',
  'import-csv-rule-2': '2. 以下有用到多國語言的欄位名稱以 {langExpression} 表示對應的語言代碼, 例如主詞條的欄位 source-entry-{langExpression} 套用藏文後變為 source-entry-bo',
  'import-csv-rule-3': '3. 支援的欄位名稱有: {supportedColumnNames}',
  'import-csv-rule-4': '4. 第一行必須定義欄位, 而且必須包含一個主詞條 source-entry-[lang], 範例檔案請參考',
  'import-csv-rule-5': '5. 如果覺得匯入期間操作會不順暢可以嘗試把設定頁的寫入延遲加長',
  'interface-font-size': '介面字體大小',
  'large': '大',
  'login': '登入',
  'matched-message': '有 {count} 個結果符合關鍵字 {keyword}',
  'medium': '中',
  'next-page': '下一頁',
  'no-column-row-detected': '在 {errorFilename} 偵測不到欄位資訊',
  'original-lang': '原文 - {lang}',
  'page-num': '頁碼',
  'please-input-exact-the-same-folder-name': '請輸入{folderName}',
  'prev-page': '上一頁',
  'recycle-bin': '資源回收桶',
  'restore': '復原',
  'search-entries': '搜尋詞條...',
  'sect': '宗派',
  'sect-1': '舊',
  'sect-2': '當',
  'sect-3': '薩',
  'sect-4': '噶',
  'sect-5': '香',
  'sect-6': '斷',
  'sect-7': '時',
  'sect-8': '依',
  'see-imported-folder': '看看新匯入的資料夾',
  'settings': '設定',
  'sign-out': '登出',
  'small': '小',
  'source': '出處',
  'source-entry': '主詞條',
  'source-entry-lang': '主詞條 - {lang}',
  'source-lang': '出處 - {lang}',
  'source-language': '來源語言',
  'submit': '送出',
  'target-entry-lang': '詞條 - {lang}',
  'target-language': '目標語言',
  'title-confirm-clear-recycle-bin-dialog': '確認清除資源回收桶',
  'title-confirm-delete-dialog': '確認刪除詞條',
  'update': '更新',
  'very-large': '非常大',
  'very-small': '非常小',
  'write-delay-with-num': '寫入延遲時間 {writeDelay} 毫秒',
  'zh-CN': '簡體中文',
  'zh-TW': '繁體中文'
};
