module.exports = {
  'field-source-language-required': '必須填寫來源語言',
  'choose-at-least-one-target-language': '請至少選擇一個目標語言',
  'choose-at-least-one-content-field': '請至少選擇一個內容欄位',
  'folder-name-taken': '資料夾名稱 {folderName} 已經存在',
  'folder-name-required': '必須填寫資料夾名稱',
  'back': '上一頁',
  'next-page': '下一頁',
  'prev-page': '上一頁',
  'folder-has-been-updated': '已更新資料夾 {folderName}',
  'folder-has-been-created': '已建立資料夾 {folderName}',
  'update': '更新',
  'edit-folder': '編輯資料夾',
  'edit': '編輯',
  'add-folder': '新增資料夾',
  'en': '英文',
  'zh-TW': '繁體中文',
  'zh-CN': '簡體中文',
  'bo': '藏文',
  'garchen': '噶千',
  'settings': '設定',
  'app-language': '應用程式語言',
  'home': '首頁',
  'folders': '資料夾',
  'about': '關於',
  'login': '登入',
  'folder-name': '資料夾名稱',
  'source-language': '來源語言',
  'target-language': '目標語言',
  'target-entry-lang': '詞條 - {lang}',
  'category': '類別',
  'sect': '宗派',
  'explaination-lang': '解釋 - {lang}',
  'original-lang': '原文 - {lang}',
  'source-lang': '出處 - {lang}',
  'content-fields': '內容欄位'
};
